version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    command: >
      sh -c "
        npx prisma migrate dev --name init &&
        npx prisma generate &&
        yarn dev
      "
    networks:
      - app-network
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: >
      sh -c "
        rm -rf node_modules &&
        yarn cache clean &&
        yarn install &&
        yarn dev
      "
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
